# Generated by Django 3.0.3 on 2020-02-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/projects/photo', verbose_name='Фото')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Отзыв клиента')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProjectCategory')),
            ],
        ),
    ]
